// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Account struct {
	AccountNumber int64     `json:"account_number"`
	UserName      string    `json:"user_name"`
	Email         string    `json:"email"`
	Balance       int64     `json:"balance"`
	Currency      string    `json:"currency"`
	CreatedAt     time.Time `json:"created_at"`
}

type Transaction struct {
	TransactionID int64     `json:"transaction_id"`
	AccountNumber int64     `json:"account_number"`
	Amount        int64     `json:"amount"`
	CreatedAt     time.Time `json:"created_at"`
}

type Transfer struct {
	TransferID        int64     `json:"transfer_id"`
	FromAccountNumber int64     `json:"from_account_number"`
	ToAccountNumber   int64     `json:"to_account_number"`
	Amount            int64     `json:"amount"`
	CreatedAt         time.Time `json:"created_at"`
}

type User struct {
	UserName          string    `json:"user_name"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
