# name: ci-test

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   test:
#     name: Test
#     runs-on: ubuntu-latest
#     steps:

#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: '1.22'
#       id: go
    
#     - name: Check out code into the Go module directory
#       uses: actions/checkout@v2

#     - name: Test
#       run: go test -v ./...

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
        id: go

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Set Environment Variables
        env:
          DB_DRIVER: ${{ secrets.DB_DRIVER }}
          DB_SOURCE: ${{ secrets.DB_SOURCE }}
        run: echo "Environment variables set."

      - name: Test
        env:
          DB_DRIVER: ${{ secrets.DB_DRIVER }}
          DB_SOURCE: ${{ secrets.DB_SOURCE }}
        run: go test -v ./...
